"""default values"""
import pygame


""""Base"""
POS_X = 0
POS_Y = 1
BEGIN = 0
END = -1
YES = 1
NO = 0


"""Direction"""
LEFT = 1
DOWN = 2
RIGHT = 3
UP = 4

"""Color"""
BLACK = (0, 0, 0)
WHITE = (255,255,255)
RED = (255, 0, 0)
GREEN = (0,255,0)
DARK_GREEN = (0,100,0)
BLUE = (0, 0, 255)
SCREEN_BACKGROUND = (100,200,255)

"""Font alignment enumerations""" # alignment : 정렬
TOP_LEFT = 0
TOP_MIDDLE = 1
TOP_RIGHT = 2
CENTER_LEFT = 3
CENTER_MIDDLE = 4
CENTER_RIGHT = 5
BOTTOM_LEFT = 6
BOTTOM_MIDDLE = 7
BOTTOM_RIGHT = 8

"""Snake"""
SNAKE_HEAD = -1
SNAKE_TAIL = 0

DIRECTION = 2
# defaultSpeed = 30
# defaultThick = 20

"""Skin"""
SKIN_HEAD = 0
SKIN_BODY = 1
SKIN_TAIL = 2
SKIN_FIRST = 3

"""Skin Name"""
SKIN_DEFAULT = 0


"""Item"""
CONTINUANCE = -1
# DEFAULT_ITEM_SIZE = defaultThick
DEFAULT_ITEM_SIZE = 30
ITEM_LIST = ["apple"]
APPLE = 0

"""User Event"""
ON_TICK = pygame.USEREVENT + 1
CRASH_WALL = pygame.USEREVENT + 2
CRASH_ITEM = pygame.USEREVENT + 3
CRASH_ITSELF = pygame.USEREVENT + 4
CRASH_OTHER_SNAKE = pygame.USEREVENT + 5


"""Screen"""
WALL_TICK = 0
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 800
SCREEN_MID = (SCREEN_WIDTH/2, SCREEN_HEIGHT/2)
SPRITE_OFFSET = ((WALL_TICK, SCREEN_WIDTH - WALL_TICK) ,(WALL_TICK, SCREEN_HEIGHT - WALL_TICK))
ITEM_MARGIN = 0
ANTI_ALIAS = True

FRAMES_PER_SECOND = 200.0
SCREEN_AUTO_UPDATE = True

DEFAULT_FONT_SIZE = 20
DEFAULT_FONT_TYPE = "comicsansms"


"""game name"""
PLAYER1_HIGH_SCORE = 0
PLAYER2_HIGH_SCORE = 1
PLAYER2_COMPETE = 2

"""Files"""
READ = "r"
WRITE = "w"
APPEND = "a"
